logger:
  file:
    path: /var/log/open5gs/smf3.log

global:
  max:
    ue: 1024

smf:
  sbi:
    server:
      - address: 127.0.0.34
        port: 7777
    client:
      scp:
        - uri: http://127.0.0.200:7777
  pfcp:
    server:
      - address: 127.0.0.34
    client:
      upf:
        - address: 127.0.0.9
  gtpc:
    server:
      - address: 127.0.0.34
  gtpu:
    server:
      - address: 127.0.0.34
  metrics:
    server:
      - address: 127.0.0.34
        port: 9092
  session:
    - subnet: 10.47.0.0/16
      gateway: 10.47.0.1
  dns:
    - 8.8.8.8
    - 8.8.4.4
  mtu: 1400
  info:
    - s_nssai:
        - sst: 3
          dnn:
            - internet
